export const tags = [
  { name: "Cool", subName: "Cool", results: 350 },
  { name: "Beautiful", subName: "Beautifl", results: 210 },
  { name: "Easy", subName: "Easy", results: 190 },
  { name: "Summary", subName: "Summary", results: 105 },
  { name: "Hot", subName: "Hot", results: 80 },
  { name: "Passage Specific", subName: "Passage Specific", results: 50 },
  { name: "Very long taaaaaaa", subName: "Very long taaaaaaa", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
  { name: "Tag", subName: "Tag", results: 50 },
];
